#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_AD_cooperative_matrix : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer BufF16 {
    float16_t data[];
} bufF16;

layout(set = 0, binding = 1) buffer BufI8 {
    int8_t data[];
} bufI8;

layout(set = 0, binding = 2) buffer BufU16 {
    uint16_t data[];
} bufU16;

void main()
{
    const vec2 shape16x8 = vec2(16.0, 8.0);
    const vec2 shape8x8 = vec2(8.0, 8.0);
    const vec2 shape8x16 = vec2(8.0, 16.0);
    const vec2 shape16x16 = vec2(16.0, 16.0);
    const vec2 shape4x16 = vec2(4.0, 16.0);
    const vec2 shape16x4 = vec2(16.0, 4.0);
    const vec2 shape4x4 = vec2(4.0, 4.0);

    coopmatAD<float16_t, 16, 8> fA, fC, fR;
    coopmatAD<float16_t, 8, 8> fB;

    coopMatLoadAD(fA, bufF16.data, shape16x8, vec2(1.0, 2.0), RowMajorAD);
    coopMatLoadAD(fB, bufF16.data, shape8x8, vec2(3.0, 4.0), ColumnMajorAD);
    coopMatLoadAD(fC, bufF16.data, shape16x8, vec2(5.0, 6.0), RowMajorAD);
    coopMatMulAD(fR, fA, fB);
    coopMatMulAddAD(fC, fA, fB, fC);
    fR = coopMatReduceAD(fC, ReduceRowAD, ReduceAddAD);
    coopMatStoreAD(fR, bufF16.data, shape16x8, vec2(7.0, 8.0), ColumnMajorAD);
    int lf = fR.length();

    coopmatAD<int8_t, 16, 8> iA;
    coopmatAD<int8_t, 8, 16> iB;
    coopmatAD<int8_t, 16, 16> iC, iR;

    coopMatLoadAD(iA, bufI8.data, shape16x8, vec2(9.0, 10.0), RowMajorAD);
    coopMatLoadAD(iB, bufI8.data, shape8x16, vec2(11.0, 12.0), ColumnMajorAD);
    coopMatLoadAD(iC, bufI8.data, shape16x16, vec2(13.0, 14.0), RowMajorAD);
    coopMatMulAD(iR, iA, iB);
    coopMatMulAddAD(iC, iA, iB, iC);
    iR = coopMatReduceAD(iC, ReduceColumnAD, ReduceMinAD);
    coopMatStoreAD(iR, bufI8.data, shape16x16, vec2(15.0, 16.0), ColumnMajorAD);
    int li = iR.length();

    coopmatAD<uint16_t, 4, 16> uA;
    coopmatAD<uint16_t, 16, 4> uB;
    coopmatAD<uint16_t, 4, 4> uC, uR;

    coopMatLoadAD(uA, bufU16.data, shape4x16, vec2(17.0, 18.0), RowMajorAD);
    coopMatLoadAD(uB, bufU16.data, shape16x4, vec2(19.0, 20.0), ColumnMajorAD);
    coopMatLoadAD(uC, bufU16.data, shape4x4, vec2(21.0, 22.0), RowMajorAD);
    coopMatMulAD(uR, uA, uB);
    coopMatMulAddAD(uC, uA, uB, uC);
    uR = coopMatReduceAD(uC, ReduceRowAD, ReduceMaxAD);
    coopMatStoreAD(uR, bufU16.data, shape4x4, vec2(23.0, 24.0), ColumnMajorAD);
    int lu = uR.length();

    if (lf + li + lu == 0) {
        fC = fR;
        iC = iR;
        uC = uR;
    }
}
