#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_AZD_neural_matrix : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer Buf { float16_t data[]; } buf;

coopmatAZD<float16_t, 16, 16> makeAcc(coopmatAZD<float16_t, 16, 16> A,
                                       coopmatAZD<float16_t, 16, 16> B,
                                       coopmatAZD<float16_t, 16, 16> C);

coopmatAZD<float16_t, 16, 16> wrapper(coopmatAZD<float16_t, 16, 16> A,
                                       coopmatAZD<float16_t, 16, 16> B,
                                       coopmatAZD<float16_t, 16, 16> C)
{
    return makeAcc(A, B, C);
}

void main()
{
    const vec2 shape = vec2(16.0, 16.0);
    const vec2 zeroOffset = vec2(0.0, 0.0);

    coopmatAZD<float16_t, 16, 16> A, B, C;
    coopmatAZD<float16_t, 16, 16> B2, C2, D1;

    coopMatLoadAZD(A, buf.data, shape, zeroOffset, gl_RowMajorAZD);
    coopMatLoadAZD(B, buf.data, shape, zeroOffset, gl_RowMajorAZD);
    coopMatLoadAZD(C, buf.data, shape, zeroOffset, gl_RowMajorAZD);
    coopMatLoadAZD(B2, buf.data, shape, zeroOffset, gl_RowMajorAZD);
    coopMatLoadAZD(C2, buf.data, shape, zeroOffset, gl_RowMajorAZD);

    coopMatMulAddAZD(D1, wrapper(A, B, C), B2, C2);
}

coopmatAZD<float16_t, 16, 16> makeAcc(coopmatAZD<float16_t, 16, 16> A,
                                       coopmatAZD<float16_t, 16, 16> B,
                                       coopmatAZD<float16_t, 16, 16> C)
{
    coopmatAZD<float16_t, 16, 16> D;
    coopMatMulAddAZD(D, A, B, C);
    return D;
}
