#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_AZD_neural_matrix : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer Buf { float16_t data[]; } buf;

void main()
{
    const vec2 shape = vec2(16.0, 16.0);
    const vec2 zeroOffset = vec2(0.0, 0.0);

    coopmatAZD<float16_t, 16, 16> A, B, C;
    coopmatAZD<float16_t, 16, 16> D0, D1;

    coopMatLoadAZD(A, buf.data, shape, zeroOffset, gl_RowMajorAZD);
    coopMatLoadAZD(B, buf.data, shape, zeroOffset, gl_RowMajorAZD);
    coopMatLoadAZD(C, buf.data, shape, zeroOffset, gl_RowMajorAZD);

    coopMatMulAddAZD(D0, A, B, C);
    coopMatMulAddAZD(D1, D0, B, C);
}
