#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_HW_neural_shader : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer Buf { float16_t data[]; } buf;

void main()
{
    const uint offset = 0;
    const uint stride = 16;
    bool cond = gl_LocalInvocationID.x == 0u;

    coopmatHW<float16_t, 16, 16> X, Y;
    coopmatHW<float16_t, 16, 16> A, B, C;
    coopmatHW<float16_t, 16, 16> D0, D1, D2, D3;

    coopMatLoadHW(X, buf.data, offset, stride, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(Y, buf.data, offset, stride, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(A, buf.data, offset, stride, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(B, buf.data, offset, stride, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(C, buf.data, offset, stride, gl_CooperativeMatrixLayoutRowMajorHW);

    if (cond) {
        coopMatMulAddHW(D0, X, B, C);
    } else {
        coopMatMulAddHW(D1, A, B, X);
    }

    coopMatMulAddHW(D2, Y, B, C);
    for (int i = 0; i < 4; ++i) {
        coopMatMulAddHW(D3, A, B, Y);
    }
}
