#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_AD_cooperative_vector : enable
#extension GL_NV_cooperative_vector : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

void main()
{
    coopvecAD<float, 5> vAD;
    coopvecNV<float, 5> vNV;

    vAD = vNV;
    vNV = vAD;
    coopvecAD<float, 5>(vNV);

    coopvecAD<float> bad1;
    coopvecAD<float, 0> bad2;
    coopvecAD<float, -1> bad3;
    coopvecAD<float, float> bad4;
}
