#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_AZD_neural_matrix : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    coopmatAZD<float, 4, 4> a4;
    coopmatAZD<float, 4, 4> b4;
    coopmatAZD<float, 4, 4> c4;
    coopmatAZD<float, 4, 4> d4;

    coopMatMulAddAZD(d4, a4, b4, c4);

    coopmatAZD<float, 3, 4> aTail;
    coopmatAZD<float, 4, 5> bTail;
    coopmatAZD<float, 3, 5> cTail;
    coopmatAZD<float, 3, 5> dTail;

    coopMatMulAddAZD(dTail, aTail, bTail, cTail);
}
