#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_AD_cooperative_matrix : enable
#extension GL_AD_cooperative_vector : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

coopvecAD<float16_t, 1> foo(coopvecAD<float16_t, 1> x) { return x; }
coopvecAD<float16_t, 2> foo(coopvecAD<float16_t, 2> x) { return x; }

void main()
{
    coopvecAD<float, 5> v = coopvecAD<float, 5>(0.0);

    vec3 x = vec3(1.0), y = vec3(2.0);
    coopvecAD<float, 5> v2 = coopvecAD<float, 5>(x, y);

    coopvecAD<float16_t, 5> v3 = coopvecAD<float16_t, 5>(v2);
    coopvecAD<float, 5> v4;

    v4 = v + v2;
    v4 = v - v2;
    v4 = v * v2;
    v4 = v / v2;

    float f = 0.0;
    v4 *= f;
    v4 *= 5.0;

    int len = v4.length();
    v4[0] = f;
    v4[4] = 5.0;

    coopvecAD<float, 20> v7;
    coopvecAD<float, 100> v8;
    coopvecAD<float16_t, 20> v7h;
    coopvecAD<float, 100> v8bias;
    coopmatAD<float16_t, 100, 20> m8;
    coopVecMatMulAD(v8, v7h, m8);

    coopvecAD<int8_t, 20> v9;
    coopvecAD<int32_t, 100> v10;
    coopvecAD<int32_t, 100> v10bias;
    coopmatAD<int8_t, 100, 20> m10;
    coopVecMatMulAD(v10, v9, m10);

    coopvecAD<float16_t, 2> f162 = coopvecAD<float16_t, 2>(v7.length());

    float16_t f16;
    coopvecAD<float16_t, 1> f161 = coopvecAD<float16_t, 1>(f16);

    coopvecAD<float16_t, 7> v11, v12, v13;
    v11 = max(v11, v12);
    v11 = min(v11, v12);
    v11 = step(v11, v12);
    v11 = clamp(v11, v12, v13);
    v11 = -v11;
    v11 = exp(v11);
    v11 = log(v11);
    v11 = tanh(v11);
    v11 = atan(v11);
    v11 = fma(v11, v12, v13);

    coopvecAD<int16_t, 7> s11, s12;
    s11 = -s11;
    s11 = ~s11;
    s11 = s11 + s12;
    s11 = s11 - s12;
    s11 = s11 * s12;
    s11 = s11 / s12;
    s11 += s12;
    s11 -= s12;
    s11 *= s12;
    s11 /= s12;

    coopvecAD<uint16_t, 7> u11, u12, u13;
    u11 = min(u11, u12);
    u11 = max(u11, u12);
    u11 = clamp(u11, u12, u13);
    u11 = ~u11;
    u11 = u11 >> u12;
    u11 = u11 << u12;
    u11 = u11 | u12;
    u11 = u11 & u12;
    u11 = u11 ^ u12;
    u11 = u11 + u12;
    u11 = u11 - u12;
    u11 = u11 * u12;
    u11 = u11 / u12;
    u11 >>= u12;
    u11 <<= u12;
    u11 |= u12;
    u11 &= u12;
    u11 ^= u12;
    u11 += u12;
    u11 -= u12;
    u11 *= u12;
    u11 /= u12;

    s11 = s11 >> s12;
    s11 = s11 << s12;
    s11 = s11 | s12;
    s11 = s11 & s12;
    s11 = s11 ^ s12;
    s11 >>= s12;
    s11 <<= s12;
    s11 |= s12;
    s11 &= s12;
    s11 ^= s12;

    coopVecMatMulAddAD(v8, v7h, m8, v8bias);
    coopVecMatMulAddAD(v10, v9, m10, v10bias);

    f += (v += v)[len];
}
