#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_AD_cooperative_matrix : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer Buf {
    float16_t data[];
} buf;

void main()
{
    coopmatAD<float16_t, 16, 8> A = coopmatAD<float16_t, 16, 8>(0.0);
    coopmatAD<float16_t, 8, 8> B = coopmatAD<float16_t, 8, 8>(1.0);
    coopmatAD<float16_t, 16, 8> C;

    coopMatLoadAD(C, buf.data, 0, 16, false);
    C = coopMatMulAddAD(A, B, C);
    coopMatStoreAD(C, buf.data, 0, 16, false);

    int len = C.length();
    coopmatAD<float16_t, 16, 8> D = coopmatAD<float16_t, 16, 8>(C);
    C = D;
    if (len == 0)
        C = coopmatAD<float16_t, 16, 8>(0.0);
}
