#version 450 core
#extension GL_EXT_scalar_block_layout : require
#extension GL_HW_neural_shader : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputX {
    float x[];
} inX;

layout(scalar, set = 0, binding = 1) uniform InputW {
    float w[128];
} inW;

layout(set = 0, binding = 2) buffer OutputY {
    float y[];
} outY;

layout(set = 0, binding = 3) buffer OutputM {
    float m[];
} outM;

void main()
{
    const ivec2 vecShape = ivec2(16, 8);
    const ivec2 matShape = ivec2(4, 4);
    const ivec2 zeroOffset = ivec2(0);

    coopvecHW<float, 16> x;
    coopmatHW<float, 16, 8> w;
    coopvecHW<float, 8> bias = coopvecHW<float, 8>(
        -0.75, -0.5, -0.25, 0.0,
         0.25, 0.5, 0.75, -0.75);
    coopvecHW<float, 8> y;

    coopmatHW<float, 4, 4> a = coopmatHW<float, 4, 4>(1.0);
    coopmatHW<float, 4, 4> b = coopmatHW<float, 4, 4>(2.0);
    coopmatHW<float, 4, 4> c = coopmatHW<float, 4, 4>(3.0);
    coopmatHW<float, 4, 4> d;

    coopVecLoadHW(x, inX.x, 0u);
    coopMatLoadHW(w, inW.w, vecShape, zeroOffset, gl_RowMajorHW);
    coopVecMatMulAddHW(y, x, w, bias);
    coopVecStoreHW(y, outY.y, 0u);

    coopMatMulAddHW(d, a, b, c);
    coopMatStoreHW(d, outM.m, matShape, zeroOffset, gl_RowMajorHW);
}
