#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_AD_cooperative_vector : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable
#extension GL_EXT_buffer_reference : enable
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer MatrixBuf {
    u64vec3 matrixData[];
} matrixBuf;

layout(set = 0, binding = 0) buffer MatrixBuf2 {
    coherent float16_t matrixData[];
} matrixBuf2;

layout(set = 0, binding = 0) coherent buffer MatrixBuf3 {
    volatile float32_t matrixData[];
} matrixBuf3;

layout(set = 0, binding = 0, buffer_reference) buffer MatrixBuf4 {
    coherent float16_t matrixData[];
};

shared uint32_t matrixShmem[100];

void main()
{
    coopvecAD<float, 5> v;

    coopVecLoadAD(v, matrixBuf.matrixData);
    coopVecStoreAD(v, matrixBuf.matrixData);

    coopVecLoadAD(v, matrixBuf2.matrixData);
    coopVecStoreAD(v, matrixBuf2.matrixData);

    coopVecLoadAD(v, matrixBuf3.matrixData);
    coopVecStoreAD(v, matrixBuf3.matrixData);

    MatrixBuf4 matrixBuf4;
    coopVecLoadAD(v, matrixBuf4.matrixData);
    coopVecStoreAD(v, matrixBuf4.matrixData);

    coopVecLoadAD(v, matrixShmem);
    coopVecStoreAD(v, matrixShmem);
}
