#version 450 core
#extension GL_AZD_cooperative_vector : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1) in;

void main()
{
    coopvecAZD<float16_t, 5> f16;
    coopvecAZD<int16_t, 5> i16;
    coopvecAZD<uint16_t, 5> u16;
    coopvecAZD<float, 5> f32;
    coopvecAZD<int, 5> i32;
    coopvecAZD<uint, 5> u32;

    i16 = float16BitsToInt16(f16);
    u16 = float16BitsToUint16(f16);
    u16 = halfBitsToUint16(f16);
    f16 = int16BitsToFloat16(i16);
    f16 = int16BitsToHalf(i16);
    f16 = uint16BitsToFloat16(u16);
    f16 = uint16BitsToHalf(u16);

    i32 = floatBitsToInt(f32);
    u32 = floatBitsToUint(f32);
    f32 = intBitsToFloat(i32);
    f32 = uintBitsToFloat(u32);
}
