#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_HW_neural_shader : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer BufF16 {
    float16_t data[];
} bufF16;

layout(set = 0, binding = 1) buffer BufI8 {
    int8_t data[];
} bufI8;

layout(set = 0, binding = 2) buffer BufI16 {
    i16vec3 data[];
} bufI16;

layout(constant_id=0) const int Rows = 16;
layout(constant_id=1) const int Columns = 16;

void main()
{
    coopmatHW<float16_t, (2*Rows), Columns> matA;

    coopMatLoadHW(matA, bufF16.data, 32u * gl_WorkGroupID.x, 512u, 0);

    coopmatHW<float16_t, 16, 8> fA, fC, fR;
    coopmatHW<float16_t, 8, 8> fB;
    coopmatHW<float, 8, 8> fMulR;

    coopMatLoadHW(fA, bufF16.data, 16u, 16u, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(fB, bufF16.data, 32u, 16u, gl_CooperativeMatrixLayoutColumnMajorHW);
    coopMatLoadHW(fC, bufF16.data, 48u, 16u, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatMulHW(fMulR, fB, fB);
    coopMatMulAddHW(fC, fA, fB, fC);
    fR = coopMatReduceHW(fC, gl_CooperativeMatrixReduceRowHW, gl_CooperativeMatrixReduceAddHW);
    coopMatStoreHW(fR, bufF16.data, 64u, 16u, gl_CooperativeMatrixLayoutColumnMajorHW);
    int lf = fR.length() + fMulR.length();

    coopmatHW<int8_t, 16, 8> iA;
    coopmatHW<int8_t, 8, 16> iB;
    coopmatHW<int8_t, 16, 16> iC, iOperand, iR;
    coopmatHW<int, 16, 16> iMulR;

    coopMatLoadHW(iA, bufI8.data, 16u, 32u, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(iB, bufI8.data, 32u, 32u, gl_CooperativeMatrixLayoutColumnMajorHW);
    coopMatLoadHW(iC, bufI8.data, 48u, 32u, gl_CooperativeMatrixLayoutRowMajorHW);
    iOperand = iC;
    coopMatMulHW(iMulR, iOperand, iOperand);
    coopMatMulAddHW(iC, iA, iB, iC);
    iR = coopMatReduceHW(iC, gl_CooperativeMatrixReduceColumnHW, gl_CooperativeMatrixReduceMinHW);
    coopMatStoreHW(iR, bufI8.data, 64u, 32u, gl_CooperativeMatrixLayoutColumnMajorHW);
    int li = iR.length() + iMulR.length();

    coopmatHW<int16_t, 4, 16> sA;
    coopmatHW<int16_t, 16, 4> sB;
    coopmatHW<int16_t, 4, 4> sC, sOperand, sR;
    coopmatHW<int, 4, 4> sMulR;

    coopMatLoadHW(sA, bufI16.data, 16u, 16u, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(sB, bufI16.data, 32u, 16u, gl_CooperativeMatrixLayoutColumnMajorHW);
    coopMatLoadHW(sC, bufI16.data, 48u, 16u, gl_CooperativeMatrixLayoutRowMajorHW);
    sOperand = sC;
    coopMatMulHW(sMulR, sOperand, sOperand);
    coopMatMulAddHW(sC, sA, sB, sC);
    sR = coopMatReduceHW(sC, gl_CooperativeMatrixReduceRowHW, gl_CooperativeMatrixReduceMaxHW);
    coopMatStoreHW(sR, bufI16.data, 64u, 16u, gl_CooperativeMatrixLayoutColumnMajorHW);
    int ls = sR.length() + sMulR.length();

    if (lf + li + ls == 0) {
        coopMatStoreHW(matA, bufF16.data, 32u * gl_WorkGroupID.x, 512u, 0);
        fC = fR;
        iC = iR;
        sC = sR;
    }
}
