#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_HW_neural_shader : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    coopvecHW<float, 100> result;
    coopvecHW<float16_t, 100> vInput;
    coopvecHW<float16_t, 99> badBias;
    coopmatHW<float16_t, 100, 20> matrix;

    coopVecMatMulAddHW(result, vInput, matrix, badBias);
}
