#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_HW_neural_shader : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    coopmatHW<float, 2, 3> floatA;
    coopmatHW<float16_t, 3, 4> halfB;
    coopmatHW<float16_t, 2, 4> halfAccumulator;

    coopMatMulAddHW(halfAccumulator, floatA, halfB, halfAccumulator);
}
