#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_AD_cooperative_matrix : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    coopmatAD<float16_t, 16, 8> f16;
    coopmatAD<float, 16, 8> f32;
    coopmatAD<int, 16, 8> i32;
    coopmatAD<uint, 16, 8> u32;
    coopmatAD<int16_t, 16, 8> i16;
    coopmatAD<uint16_t, 16, 8> u16;

    u32 = coopmatAD<uint, 16, 8>(f16);
    i32 = coopmatAD<int, 16, 8>(f16);
    i16 = coopmatAD<int16_t, 16, 8>(f32);
    u16 = coopmatAD<uint16_t, 16, 8>(f32);

    i32 = coopmatAD<int, 16, 8>(i16);
    u32 = coopmatAD<uint, 16, 8>(u16);

    f32 = coopmatAD<float, 16, 8>(u16);
    f16 = coopmatAD<float16_t, 16, 8>(i16);
    f16 = coopmatAD<float16_t, 16, 8>(f32);
}
