#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_HW_neural_shader : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    coopmatHW<float, 4, 4> a4;
    coopmatHW<float, 4, 4> b4;
    coopmatHW<float, 4, 4> c4;
    coopmatHW<float, 4, 4> d4;

    coopMatMulAddHW(d4, a4, b4, c4);

    coopmatHW<float, 3, 4> aTail;
    coopmatHW<float, 4, 5> bTail;
    coopmatHW<float, 3, 5> cTail;
    coopmatHW<float, 3, 5> dTail;

    coopMatMulAddHW(dTail, aTail, bTail, cTail);
}
