#version 450 core
#extension GL_KHR_memory_scope_semantics : enable
#extension GL_AD_cooperative_matrix : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    coopmatAD<int, 16, 8> i32;
    coopmatAD<uint8_t, 16, 8> u8;
    coopmatAD<float, 16, 8> f32;
    coopmatAD<float16_t, 16, 8> f16;

    floatBitsToInt(i32);
    uintBitsToFloat(u8);
    float16BitsToInt16(f32);
    int16BitsToFloat16(f16);
}
