#version 450 core
#extension GL_AZD_neural_matrix : enable
#extension GL_AZD_cooperative_vector : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
    coopvecAZD<float, 8> x8;
    coopvecAZD<float, 8> y8;
    coopvecAZD<float, 8> bias8;
    coopmatAZD<float, 8, 8> w8;

    coopVecMatMulAZD(y8, x8, w8);
    coopVecMatMulAddAZD(y8, x8, w8, bias8);

    coopvecAZD<float, 8> xTail;
    coopvecAZD<float, 10> yTail;
    coopmatAZD<float, 10, 8> wTail;

    coopVecMatMulAZD(yTail, xTail, wTail);
}
