#version 450 core

#extension GL_KHR_memory_scope_semantics : enable
#extension GL_AZD_neural_matrix : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InBuf { float16_t data[]; } inBuf;
layout(set = 0, binding = 1) buffer OutBuf { float16_t data[]; } outBuf;

// No matmul use. The opt pass should default this matrix type to MatrixUseAAZD.
void main()
{
    const vec2 shape = vec2(16.0, 16.0);
    const vec2 offset = vec2(0.0, 0.0);

    coopmatAZD<float16_t, 16, 16> value;

    coopMatLoadAZD(value, inBuf.data, shape, offset, gl_RowMajorAZD);
    coopMatStoreAZD(value, outBuf.data, shape, offset, gl_ColumnMajorAZD);
}
