#version 450 core
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputA { float16_t data[]; } A;
layout(set = 0, binding = 1) buffer InputB { float16_t data[]; } B;
layout(set = 0, binding = 2) buffer InputC { float16_t data[]; } C;
layout(set = 0, binding = 3) buffer OutputD { float16_t data[]; } D;

void main()
{
    for (int i = 0; i < 35; ++i) {
        D.data[i] = A.data[i];
    }
}
