#version 460 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputA { int data[]; } A;
layout(set = 0, binding = 1) buffer InputB { int data[]; } B;
layout(set = 0, binding = 2) buffer InputC { int data[]; } C;
layout(set = 0, binding = 3) buffer OutputD { int data[]; } D;

void main()
{
    for (int i = 0; i < 16; ++i)
        D.data[i] = A.data[i];
}

