#version 460 core
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputA { float16_t data[]; } A;
layout(set = 0, binding = 1) buffer InputB { float16_t data[]; } B;
layout(set = 0, binding = 2) buffer InputC { float data[]; } C;
layout(set = 0, binding = 3) buffer OutputD { float data[]; } D;

void main()
{
    for (int row = 0; row < 4; ++row) {
        for (int col = 0; col < 4; ++col) {
            float acc = C.data[row * 4 + col];
            for (int inner = 0; inner < 4; ++inner)
                acc = fma(float(A.data[row * 4 + inner]), float(B.data[inner * 4 + col]), acc);
            D.data[row * 4 + col] = acc;
        }
    }
}

