#version 450 core
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputA { float16_t data[]; } A;
layout(set = 0, binding = 1) buffer InputB { float16_t data[]; } B;
layout(set = 0, binding = 2) buffer InputC { float16_t data[]; } C;
layout(set = 0, binding = 3) buffer OutputD { float16_t data[]; } D;

void main()
{
    for (int row = 0; row < 7; ++row) {
        for (int col = 0; col < 5; ++col) {
            float16_t acc = C.data[row * 5 + col];
            for (int k = 0; k < 3; ++k) {
                acc += A.data[row * 3 + k] * B.data[k * 5 + col];
            }
            D.data[row * 5 + col] = acc;
        }
    }
}
