#version 450 core
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputX { float16_t data[]; } X;
layout(set = 0, binding = 1) buffer InputW { float16_t data[]; } W;
layout(set = 0, binding = 2) buffer InputC { float16_t data[]; } C;
layout(set = 0, binding = 3) buffer OutputY { float16_t data[]; } Y;

void main()
{
    for (int col = 0; col < 3; ++col) {
        float16_t acc = float16_t(0.0);
        for (int k = 0; k < 5; ++k) {
            acc += X.data[k] * W.data[col * 5 + k];
        }
        Y.data[col] = acc;
    }
}
