#version 450 core
#extension GL_AZD_neural_matrix : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputA { float data[]; } A;
layout(set = 0, binding = 1) buffer InputB { float data[]; } B;
layout(set = 0, binding = 2) buffer InputC { float data[]; } C;
layout(set = 0, binding = 3) buffer OutputD { float data[]; } D;

void main()
{
    const vec2 shape = vec2(8.0, 8.0);
    const vec2 zeroOffset = vec2(0.0, 0.0);

    coopmatAZD<float, 8, 8> value;
    coopMatLoadAZD(value, A.data, shape, zeroOffset, gl_RowMajorAZD);
    coopMatStoreAZD(value, D.data, shape, zeroOffset, gl_RowMajorAZD);
}
