#version 450 core
#extension GL_AZD_neural_matrix : enable
#extension GL_AZD_cooperative_vector : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputA { float16_t data[]; } A;
layout(set = 0, binding = 1) buffer InputB { float16_t data[]; } B;
layout(set = 0, binding = 2) buffer InputC { float16_t data[]; } C;
layout(set = 0, binding = 3) buffer OutputD { float16_t data[]; } D;

void main()
{
    const vec2 shape = vec2(16.0, 16.0);
    const vec2 zeroOffset = vec2(0.0, 0.0);

    coopmatAZD<float16_t, 16, 16> a;
    coopmatAZD<float16_t, 16, 16> b;
    coopmatAZD<float16_t, 16, 16> c;
    coopmatAZD<float16_t, 16, 16> d0;
    coopmatAZD<float16_t, 16, 16> d1;
    coopvecAZD<float16_t, 16> x;
    coopvecAZD<float16_t, 16> bias;
    coopvecAZD<float16_t, 16> y0;
    coopvecAZD<float16_t, 16> y1;

    coopMatLoadAZD(a, A.data, shape, zeroOffset, gl_RowMajorAZD);
    coopMatLoadAZD(b, B.data, shape, zeroOffset, gl_RowMajorAZD);
    coopMatLoadAZD(c, C.data, shape, zeroOffset, gl_RowMajorAZD);
    coopMatMulAddAZD(d0, a, b, c);
    coopMatMulAddAZD(d1, a, b, d0);
    coopMatStoreAZD(d1, D.data, shape, zeroOffset, gl_RowMajorAZD);

    coopVecLoadAZD(x, A.data);
    coopVecLoadAZD(bias, D.data);
    coopVecMatMulAddAZD(y0, x, b, bias);
    coopVecStoreAZD(y0, D.data);
    coopVecLoadAZD(bias, D.data);
    coopVecMatMulAddAZD(y1, x, b, bias);
    coopVecStoreAZD(y1, D.data);
}
