#version 450 core
#extension GL_AZD_neural_matrix : enable
#extension GL_AZD_cooperative_vector : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputX { float16_t data[]; } X;
layout(set = 0, binding = 1) buffer InputW { float16_t data[]; } W;
layout(set = 0, binding = 2) buffer InputC { float16_t data[]; } C;
layout(set = 0, binding = 3) buffer OutputY { float16_t data[]; } Y;

void main()
{
    const vec2 shapeW = vec2(3.0, 5.0);
    const vec2 zeroOffset = vec2(0.0, 0.0);

    coopvecAZD<float16_t, 5> x;
    coopmatAZD<float16_t, 3, 5> w;
    coopvecAZD<float16_t, 3> y;

    coopVecLoadAZD(x, X.data);
    coopMatLoadAZD(w, W.data, shapeW, zeroOffset, gl_RowMajorAZD);
    coopVecMatMulAZD(y, x, w);
    coopVecStoreAZD(y, Y.data);
}
