#version 450 core
#extension GL_AZD_neural_matrix : enable
#extension GL_AZD_cooperative_vector : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputX { float data[]; } X;
layout(set = 0, binding = 1) buffer InputW { float data[]; } W;
layout(set = 0, binding = 2) buffer InputBias { float data[]; } Bias;
layout(set = 0, binding = 3) buffer OutputY { float data[]; } Y;

void main()
{
    const vec2 shapeW = vec2(16.0, 32.0);
    const vec2 zeroOffset = vec2(0.0, 0.0);

    coopvecAZD<float, 32> x;
    coopmatAZD<float, 16, 32> w;
    coopvecAZD<float, 16> bias;
    coopvecAZD<float, 16> y;

    coopVecLoadAZD(x, X.data);
    coopMatLoadAZD(w, W.data, shapeW, zeroOffset, gl_RowMajorAZD);
    coopVecLoadAZD(bias, Bias.data);
    coopVecMatMulAddAZD(y, x, w, bias);
    coopVecStoreAZD(y, Y.data);
}
