#version 450 core
#extension GL_AZD_neural_matrix : enable
#extension GL_AZD_cooperative_vector : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputX { float data[]; } X;
layout(set = 0, binding = 1) buffer InputW { float data[]; } W;
layout(set = 0, binding = 2) buffer InputC { float data[]; } C;
layout(set = 0, binding = 3) buffer OutputY { float data[]; } Y;

void main()
{
    const vec2 shapeW = vec2(8.0, 16.0);
    const vec2 zeroOffset = vec2(0.0, 0.0);

    coopvecAZD<float, 16> x;
    coopmatAZD<float, 8, 16> w;
    coopvecAZD<float, 8> y;

    coopVecLoadAZD(x, X.data);
    coopMatLoadAZD(w, W.data, shapeW, zeroOffset, gl_RowMajorAZD);
    coopVecMatMulAZD(y, x, w);
    coopVecStoreAZD(y, Y.data);
}
