#version 450 core
#extension GL_HW_neural_shader : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputA { float16_t data[]; } A;
layout(set = 0, binding = 1) buffer InputB { float16_t data[]; } B;
layout(set = 0, binding = 2) buffer InputC { float16_t data[]; } C;
layout(set = 0, binding = 3) buffer OutputD { float16_t data[]; } D;

void main()
{
    const ivec2 shape = ivec2(8.0, 8.0);
    const ivec2 zeroOffset = ivec2(0.0, 0.0);

    coopmatHW<float16_t, 8, 8> value;
    coopMatLoadHW(value, A.data, shape, zeroOffset, gl_RowMajorHW);
    coopMatStoreHW(value, D.data, shape, zeroOffset, gl_RowMajorHW);
}
