#version 450 core
#extension GL_HW_neural_shader : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputA { float data[]; } A;
layout(set = 0, binding = 1) buffer InputB { float data[]; } B;
layout(set = 0, binding = 2) buffer InputC { float data[]; } C;
layout(set = 0, binding = 3) buffer OutputD { float data[]; } D;

void main()
{
    const ivec2 shape = ivec2(8.0, 8.0);
    const ivec2 zeroOffset = ivec2(0.0, 0.0);

    coopmatHW<float, 8, 8> value;
    coopMatLoadHW(value, A.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatStoreHW(value, D.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
}
