#version 460 core
#extension GL_HW_neural_shader : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputA { uint16_t data[]; } A;
layout(set = 0, binding = 1) buffer InputB { uint16_t data[]; } B;
layout(set = 0, binding = 2) buffer InputC { uint16_t data[]; } C;
layout(set = 0, binding = 3) buffer OutputD { uint16_t data[]; } D;

void main()
{
    coopmatHW<uint16_t, 4, 4> value;
    coopMatLoadHW(value, A.data, ivec2(4), ivec2(0), gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatStoreHW(value, D.data, ivec2(4), ivec2(0), gl_CooperativeMatrixLayoutRowMajorHW);
}

