#version 460 core
#extension GL_HW_neural_shader : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputA { int data[]; } A;
layout(set = 0, binding = 1) buffer InputB { int data[]; } B;
layout(set = 0, binding = 2) buffer InputC { int data[]; } C;
layout(set = 0, binding = 3) buffer OutputD { int data[]; } D;

void main()
{
    coopmatHW<int, 4, 4> value;
    coopMatLoadHW(value, A.data, ivec2(4), ivec2(0), gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatStoreHW(value, D.data, ivec2(4), ivec2(0), gl_CooperativeMatrixLayoutRowMajorHW);
}

