#version 450 core
#extension GL_HW_neural_shader : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputA { float data[]; } A;
layout(set = 0, binding = 1) buffer InputB { float data[]; } B;
layout(set = 0, binding = 2) buffer InputC { float data[]; } C;
layout(set = 0, binding = 3) buffer OutputD { float data[]; } D;

void main()
{
    const ivec2 shape = ivec2(32.0, 32.0);
    const ivec2 zeroOffset = ivec2(0.0, 0.0);

    coopmatHW<float, 32, 32> a;
    coopmatHW<float, 32, 32> b;
    coopmatHW<float, 32, 32> c;
    coopmatHW<float, 32, 32> d;

    coopMatLoadHW(a, A.data, shape, zeroOffset, gl_RowMajorHW);
    coopMatLoadHW(b, B.data, shape, zeroOffset, gl_RowMajorHW);
    coopMatLoadHW(c, C.data, shape, zeroOffset, gl_RowMajorHW);
    coopMatMulAddHW(d, a, b, c);
    coopMatStoreHW(d, D.data, shape, zeroOffset, gl_RowMajorHW);
}
