#version 460 core
#extension GL_HW_neural_shader : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputA { float16_t data[]; } A;
layout(set = 0, binding = 1) buffer InputB { float16_t data[]; } B;
layout(set = 0, binding = 2) buffer InputC { float16_t data[]; } C;
layout(set = 0, binding = 3) buffer OutputD { float16_t data[]; } D;
layout(set = 0, binding = 4) buffer OutputE { float16_t data[]; } E;

void main()
{
    const ivec2 shape = ivec2(32);
    const ivec2 zeroOffset = ivec2(0);

    coopmatHW<float16_t, 32, 32> a;
    coopmatHW<float16_t, 32, 32> w;
    coopmatHW<float16_t, 32, 32> c;
    coopmatHW<float16_t, 32, 32> d;

    coopMatLoadHW(a, A.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(w, B.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(c, C.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);

    coopMatMulAddHW(d, a, w, c);

    coopMatStoreHW(d, D.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatStoreHW(w, E.data, shape, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
}
