#version 450 core
#extension GL_HW_neural_shader : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputA { float data[]; } A;
layout(set = 0, binding = 2) buffer InputC { float data[]; } C;
layout(set = 0, binding = 3) buffer OutputD { float data[]; } D;

void main()
{
    const ivec2 shapeA = ivec2(4, 4);
    const ivec2 shapeC = ivec2(4, 4);
    const ivec2 shapeD = ivec2(4, 4);
    const ivec2 zeroOffset = ivec2(0, 0);

    // Constant matrix B where all elements are 0.5
    coopmatHW<float, 4, 4> b = coopmatHW<float, 4, 4>(0.5);

    coopmatHW<float, 4, 4> a;
    coopmatHW<float, 4, 4> c;
    coopmatHW<float, 4, 4> d;

    coopMatLoadHW(a, A.data, shapeA, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatLoadHW(c, C.data, shapeC, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopMatMulAddHW(d, a, b, c);
    coopMatStoreHW(d, D.data, shapeD, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
}
