#version 450 core
#extension GL_HW_neural_shader : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputX { float data[]; } X;
layout(set = 0, binding = 1) buffer InputW { float data[]; } W;
layout(set = 0, binding = 2) buffer InputBias { float data[]; } Bias;
layout(set = 0, binding = 3) buffer OutputY { float data[]; } Y;

void main()
{
    const ivec2 shapeW = ivec2(32.0, 16.0);
    const ivec2 zeroOffset = ivec2(0.0, 0.0);

    coopvecHW<float, 32> x;
    coopmatHW<float, 32, 16> w;
    coopvecHW<float, 16> bias;
    coopvecHW<float, 16> y;

    coopVecLoadHW(x, X.data, 0u);
    coopMatLoadHW(w, W.data, shapeW, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopVecLoadHW(bias, Bias.data, 0u);
    coopVecMatMulAddHW(y, x, w, bias);
    coopVecStoreHW(y, Y.data, 0u);
}
