#version 460 core
#extension GL_HW_neural_shader : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputX { float16_t data[]; } X;
layout(set = 0, binding = 1) buffer InputW { float data[]; } W;
layout(set = 0, binding = 2) buffer InputC { float data[]; } C;
layout(set = 0, binding = 3) buffer OutputY { float data[]; } Y;

void main()
{
    coopvecHW<float16_t, 8> x;
    coopmatHW<float, 8, 16> w;
    coopvecHW<float, 16> y;

    coopVecLoadHW(x, X.data, 0u);
    coopMatLoadHW(w, W.data, ivec2(8, 16), ivec2(0), gl_CooperativeMatrixLayoutRowMajorHW);
    coopVecMatMulHW(y, x, w);
    coopVecStoreHW(y, Y.data, 0u);
}
