#version 450 core
#extension GL_HW_neural_shader : enable
#extension GL_EXT_shader_explicit_arithmetic_types : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputX { float16_t data[]; } X;
layout(set = 0, binding = 1) buffer InputW { float16_t data[]; } W;
layout(set = 0, binding = 2) buffer InputBias { float16_t data[]; } Bias;
layout(set = 0, binding = 3) buffer OutputY { float16_t data[]; } Y;

void main()
{
    const ivec2 shapeW = ivec2(32, 16);
    const ivec2 zeroOffset = ivec2(0);

    coopvecHW<float16_t, 32> x;
    coopmatHW<float16_t, 32, 16> w;
    coopvecHW<float16_t, 16> bias;
    coopvecHW<float, 32> xf;
    coopmatHW<float, 32, 16> wf;
    coopvecHW<float, 16> biasf;
    coopvecHW<float16_t, 16> y;

    coopVecLoadHW(x, X.data, 0u);
    coopMatLoadHW(w, W.data, shapeW, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopVecLoadHW(bias, Bias.data, 0u);

    xf = coopvecHW<float, 32>(x);
    x = coopvecHW<float16_t, 32>(xf);
    wf = coopmatHW<float, 32, 16>(w);
    w = coopmatHW<float16_t, 32, 16>(wf);
    biasf = coopvecHW<float, 16>(bias);
    bias = coopvecHW<float16_t, 16>(biasf);

    coopVecMatMulAddHW(y, x, w, bias);
    coopVecStoreHW(y, Y.data, 0u);
}
