#version 450 core
#extension GL_HW_neural_shader : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputX { float data[]; } X;
layout(set = 0, binding = 1) buffer InputW { float data[]; } W;
layout(set = 0, binding = 2) buffer InputBias { float data[]; } Bias;
layout(set = 0, binding = 3) buffer OutputY { float data[]; } Y;

void main()
{
    const ivec2 shapeW = ivec2(32, 16);
    const ivec2 zeroOffset = ivec2(0);

    const coopvecHW<float, 32> zeroX = coopvecHW<float, 32>(0.0);
    const coopvecHW<float, 32> oneX = coopvecHW<float, 32>(1.0);
    const coopvecHW<float, 16> zeroBias = coopvecHW<float, 16>(0.0);
    const coopvecHW<float, 16> oneBias = coopvecHW<float, 16>(1.0);

    coopvecHW<float, 32> x;
    coopmatHW<float, 32, 16> w;
    coopvecHW<float, 16> bias;
    coopvecHW<float, 16> y;

    coopVecLoadHW(x, X.data, 0u);
    coopMatLoadHW(w, W.data, shapeW, zeroOffset, gl_CooperativeMatrixLayoutRowMajorHW);
    coopVecLoadHW(bias, Bias.data, 0u);

    x = -(-x);
    x = (x + zeroX) - zeroX;
    x = (x * oneX) / oneX;
    x *= 1.0;

    bias = -(-bias);
    bias = (bias + zeroBias) - zeroBias;
    bias = (bias * oneBias) / oneBias;
    bias *= 1.0;

    coopVecMatMulAddHW(y, x, w, bias);

    y = -(-y);
    y = (y + zeroBias) - zeroBias;
    y = (y * oneBias) / oneBias;
    y *= 1.0;

    coopVecStoreHW(y, Y.data, 0u);
}
