#version 460 core
#extension GL_HW_neural_shader : require
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputX { int8_t data[]; } X;
layout(set = 0, binding = 1) buffer InputW { uint8_t data[]; } W;
layout(set = 0, binding = 2) buffer InputC { int data[]; } C;
layout(set = 0, binding = 3) buffer OutputY { int data[]; } Y;

void main()
{
    coopvecHW<int8_t, 4> x;
    coopmatHW<uint8_t, 4, 4> w;
    coopvecHW<int, 4> y;
    coopVecLoadHW(x, X.data, 0u);
    coopMatLoadHW(w, W.data, ivec2(4), ivec2(0), gl_CooperativeMatrixLayoutRowMajorHW);
    coopVecMatMulHW(y, x, w);
    coopVecStoreHW(y, Y.data, 0u);
}

